### ISSUE TITLE
Character sheet blank when opened the first time after the Actor is created

### ISSUE THREAD

**Issue by Muttley** [ben/foundry-ironsworn#1029]
Hi,

When creating a new Character Actor and the sheet opens for the first time, the contents of the sheet are blank.  If you then close and reopen the sheet it works fine.

See example here: https://youtu.be/npEYmp73ijI

Browser log: [ironsworn-character-sheet-blank.log](https://github.com/user-attachments/files/16968800/ironsworn-character-sheet-blank.log)

This is with the NodeJS version of Foundry VTT (running on Ubuntu 24.04.1

![image](https://github.com/user-attachments/assets/9bdd9e77-09ae-4c90-b6af-3b200ede3d94)

The same issue occurs with all mods disabled.

**Comment by ben** [comment]
Seems like there's a race in there having to do with the creation of the actor and the rendering of the sheet. I'm not able to reproduce this locally, but I can introduce a small delay between those two steps and see if it helps.

**Comment by ben** [comment]
Ha, managed to reproduce, and I was right. This fix will go out in the next release.

**Comment by Muttley** [comment]
> Ha, managed to reproduce, and I was right. This fix will go out in the next release.

Lovely. Thank you.

Great work on the system BTW, it's pretty slick.  :)
