### ISSUE TITLE
Cannot delete from Legacy track

### ISSUE THREAD

**Issue by minotaur05** [ben/foundry-ironsworn#1031]
Making Legacy tracks (Quests, Bonds or Discoveries), no method I can find to delete or undo if done in error.

**Comment by ben** [comment]
It's not _super_ discoverable, but there is a control - click into "edit" mode, and you'll see the "decrease progress" button:

![CleanShot 2024-09-22 at 17 39 46](https://github.com/user-attachments/assets/39d161ce-0f5d-4dc7-b31e-9289a1f85934)
