### ISSUE TITLE
Sundered Isles oracles with a cursed variant won't roll

### ISSUE THREAD

**Issue by Angrymog** [ben/foundry-ironsworn#1033]
When doing some game and character setup, I discovered that a lot of the Sundered Isles oracles don't do anything when you click on them, specifically all oracles that have a cursed variant.  The matching cursed oracle works fine - e.g. Sea Cave Features won't roll, but Sea Cave Cursed Features will.

**Comment by ben** [comment]
Odd, I'm not able to reproduce this. When I click "SI / Ruin / Ruin First Look", it rolls the cursed die, and occasionally I get a cursed result when that die comes up 💀:

![CleanShot 2024-10-30 at 17 05 58](https://github.com/user-attachments/assets/f8496db9-5396-44c6-9e37-5b10d94f5ea9)

![CleanShot 2024-10-30 at 17 06 08](https://github.com/user-attachments/assets/82065684-3181-4e74-8f8e-4d846cda35ee)

Can you be more specific in what you did to get this to happen? I'd love to fix it if it's a problem.

**Comment by Angrymog** [comment]
Nothing.  I just tried to roll it.  I double checked that the system was up to date, and even made a new world to check it wasn't something wierd and corrupted with that instance.  Will record and show you.

**Comment by Angrymog** [comment]
https://youtu.be/zHj5o_7610U - here, ten minutes of amazing clicky clicky (non) action.

**Comment by Angrymog** [comment]
As per my testing for 1034 enabling Dice So Nice makes the Oracles work properly again, regardless of any other settings in DSN or the IS/SF module.

**Comment by Angrymog** [comment]
Updated my DSN and this behavior persists - oracles with a cursed variant only roll with DSN enabled.

**Comment by ben** [comment]
Aha, it's to do with DSN not being enabled. I found the issue, it's the same as #1034. I'll ship a release in just a bit.

**Comment by ben** [comment]
Fixed in release 1.24.5, thanks!
