### ISSUE TITLE
Sometimes Burn-Button in Chart-Card yield "Undefined"

### ISSUE THREAD

**Issue by tagnullde** [ben/foundry-ironsworn#115]
Ironsworn 1.4.4
Foundry 0.8.9 (happend in 0.8.8 too)

If I get the option to burn momentum via the Chart-Card, it sometime results in an error ("Undefined") after clicking the button and no action. Burning via the Character-Sheet works as expected.

I am still trying to replicate the error below. But it doesn't happen always. (Strangely - it happend always until I started to write this issue...).It doesn't reset the momentum in the character sheet either.

![grafik](https://user-images.githubusercontent.com/44159008/130022271-ad7c264b-2700-4e51-96a1-215bba8ad920.png)

Not sure if this console log is releated.
![grafik](https://user-images.githubusercontent.com/44159008/130022425-069a098f-0756-446f-843c-02f57dd30b5d.png)

**Comment by ben** [comment]
Turns out it's easy to reproduce: this whole button logic assumed you were rolling against a move, not rolling a stat directly, so there was a bug. Fixing in a minute.

**Comment by ben** [comment]
💥 Upgrade to v1.5.0 and you'll get the fix!
