### ISSUE TITLE
Moves / Oracle Header not "pinned" when scrolling

### ISSUE THREAD

**Issue by tagnullde** [ben/foundry-ironsworn#119]
When scrolling through the moves, the "Moves / Oracle" Header stays put. But if you select "Oracles" - the header scrolls up.

![Peek 2021-08-21 19-33](https://user-images.githubusercontent.com/44159008/130330338-52a59221-3940-4ed0-9b18-55c8ea4d214b.gif)

**Comment by ben** [comment]
Fixed this, and added a search box. Thanks for the report! 1.5.1 is available for update right now.
