### ISSUE TITLE
NPCs as actors instead of items

### ISSUE THREAD

**Issue by sergeykolbasov** [ben/foundry-ironsworn#121]
Hello

I've just recently discovered this implementation of the Ironsworn system and I love it! We've started a new campaign in co-op, and it's a blast.

There is one minor issue I've encountered so far. I've imported all the foes from compendium into the world's items, and it seems there is no way to drag it onto the map for everyone to see as it doesn't have an actor representation. Also, the progress track is local to the client in that case.

It would be awesome for the coop games to see the enemies' icons in front & share the progress track between the clients during the combat.

**Comment by ben** [comment]
Have you tried the "shared" sheet for this? It can hold progress items like
foes, and also shared vows. And it's an actor, so you can place it on the
map!

– Ben

**Comment by sergeykolbasov** [comment]
Hi Ben

That's a nice option! I guess I can hack a simple script that would map all these compendium items into actors with a shared sheet. Thanks for the tip!
