### ISSUE TITLE
"Oracle - Settlement Name (Old Language)" data is missing (v1.5.1)

### ISSUE THREAD

**Issue by japatsu** [ben/foundry-ironsworn#123]
(First of all, a _huge_ **thank you** for this excellent system! Great work, keep it up!)

Settlement name (Old Language) is listed in Oracles but it doesn't do/roll anything and it seems to be missing its rollable table data completely.

![image](https://user-images.githubusercontent.com/61741172/131262176-41d7e3f9-3a4c-47e0-bef7-8730d29cbe8f.png)

**Comment by ben** [comment]
Fixed! Look for this to be released soon.

**Comment by ben** [comment]
Just released 1.5.3. Cheers!
