### ISSUE TITLE
Suggestion: notes tab on character sheets

### ISSUE THREAD

**Issue by AnneGR** [ben/foundry-ironsworn#124]
Hey! Would it be possible to add a generic 'notes' tab/box/whatever on character sheets? It would be useful for keeping track of stuff like inventory for people like me who are so inclined.

**Comment by ben** [comment]
That's a good idea. Do you think it would make sense to include that in the sheet for bonds? Now I'm wondering what other kinds of rarely-used things could be moved there. What do you think?

**Comment by AnneGR** [comment]
I think leave bonds just for bonds. They don't come up much, but they're important when they do. I was thinking something like this for notes?

![image](https://user-images.githubusercontent.com/5304785/132783743-dce8ecd3-370e-48f2-88f5-e4e662a8a1e8.png)

**Comment by SasugaTV** [comment]
I would like this very much for keeping track of specific items.

Could we also add notes tot he Party Sheet?

**Comment by ben** [comment]
I just shipped 1.10.6 with this included. Enjoy!

![CleanShot 2022-02-13 at 07 53 20](https://user-images.githubusercontent.com/39902/153761298-66614b4e-d5b9-466f-aea2-592c712398d2.jpg)

**Comment by SasugaTV** [comment]
You're awesome, thanks so much!
