### ISSUE TITLE
Can't open anything after updating to 0.2.0

### ISSUE THREAD

**Issue by olavmueller** [ben/foundry-ironsworn#13]
After updating my ironsworn system to the new 0.2.0 version I can't open any sheet. Even creating a new world and in there creating a fresh character doesn't open that sheet. 

I was using 0.0.9 previously (and thankfully still have a copy of that around here somewhere)

![image](https://user-images.githubusercontent.com/12106535/106800689-15e32280-6661-11eb-8185-9b3045a0e5b4.png)

**Comment by ben** [comment]
Huh, that's weird. I'm actually not sure why it ever worked, maybe I've got some module installed that you don't. Anyways, I just pushed 0.2.1, which should fix it. Could you check?

**Comment by olavmueller** [comment]
Yes, it does. Fixed in 0.2.1. Thanks very much.
