### ISSUE TITLE
Clear(er) Notice of Cancelled Dice Due To Negative Momentum

### ISSUE THREAD

**Issue by SasugaTV** [ben/foundry-ironsworn#136]
I'm new to Ironsworn and started using Foundry VTT to play it so it'd be easier on me keeping track of the rules. As some might notice, I thought there had been a bug when I was MISSing what looked to me should be Weak Hits.

Turns out, the die was probably being cancelled by the negative momentum I had, and being new to the game, I'd forgotten about that mechanic (which, is why I was using Foundry instead of playing with paper, given the opportunity, in the first place).

Anyway, a notification that states that the die was cancelled could be very helpful for new and experienced players alike. Experienced players could just as easily forget as a new player. In a guided game, it could save the GM headaches with other players too.

All around, I just feel it'd be a good idea to add in a notification that the die was cancelled by negative momentum, when it is.
![Ironsworn Bug Should Be Weak Hit But Is Miss](https://user-images.githubusercontent.com/38813948/136646717-4a3b224c-8e58-4da3-84b0-26ca015a7af1.png)

**Comment by ben** [comment]
You closed this one, but I actually think it's a good idea. Let me see if I can add a big red ❌ over the canceled die.

**Comment by ben** [comment]
Maybe not a big ❌, but a little bit better. Before:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/39902/136665760-3b63310a-8227-4f9d-a22f-aa0413d69fac.png">

After:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/39902/136665762-66cef540-6578-4b25-80d8-6fcb13cd7d1e.png">

I'll release this merge in just a bit. By the time you read this, you can probably hit "update" on your system and get the fix. It won't change rolls already made, but ones in the future will get this change.
