### ISSUE TITLE
Invert red and green for challenge die

### ISSUE THREAD

**Issue by AnneGR** [ben/foundry-ironsworn#144]
This is a minor cosmetic thing. Feel free to ignore.

I've noticed on challenge die rolls 1s are red and 10s are green. Since low numbers are _good_ on challenge dice perhaps make it the other way around?

Screenshots
![image](https://user-images.githubusercontent.com/5304785/136711952-c8438122-e70e-4997-846c-ce75c100d4b0.png)

![image](https://user-images.githubusercontent.com/5304785/136711963-d1b34532-39c8-470a-a7a0-d4f7be5ddf45.png)

**Comment by ben** [comment]
No, this is great! Thanks for bringing it up, I wouldn't have thought to do this but it totally makes sense.

Over in #145 I've got this going, which I think is better. What do you think?

<img width="279" alt="image" src="https://user-images.githubusercontent.com/39902/136717336-372cf848-d562-4672-8421-54991375fc54.png">
