### ISSUE TITLE
Some minor glitches

### ISSUE THREAD

**Issue by burgbach** [ben/foundry-ironsworn#15]
Hi there,

first a big thank you, I know it's not the right place, but I don't know where to discuss :-)

Testing on 0.7.9.

1) my character sheet does not contain the "Enter The Fray" move (but lots of others are here).
2) the choices moves (at the very bottom) do not work (but other oracle tables do)

Cheers,
Laurent

**Comment by rhybro** [comment]
Hi, 
I'm not sure where to discuss this either, I'm afraid. But I'm having the same issue with "Secure an Advantage" not showing up for me and the choices tables not working. I'm also on 0.7.9.  

Cheers
Rhys

**Comment by ben** [comment]
OK, this looks glitchy for sure. I'm going to rework how moves work when the actor gets created, and avoid creating a bunch of owned items.
