### ISSUE TITLE
Archive vows/progress

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#177]
Seems like it'd be nice to have a list of completed-or-abandoned vows, instead of them evaporating into nothing.

**Comment by Rooksgate** [comment]
That would be nice. Right now my players are recording outcomes as a journal entry - but a tab with completed vows would be great!

**Comment by ben** [comment]
My initial thoughts:

- This could be implemented as a flag, so no need to update `template.json` or any of the types
- Need a button to toggle the archived flag
- Need a way to view just the archived items

**Comment by Rooksgate** [comment]
All true. In the PnP you have lists of progesses that will be abandoned or completed but become a part of the permanent record.

When we started using the Foundry (and once again, thanks),  unless you wanted reams of progresses, they are deleted. If they could be flagged archived and have button to view archived progress that would be perfect.

The challenge comes that many notes attached to the actual progress (see attached example).
________________________________

**Comment by ben** [comment]
Fixed this in #257, which shipped as part of 1.10.34.
