### ISSUE TITLE
Character Sheet - Choice Oracles Don't Work

### ISSUE THREAD

**Issue by kdmcdrm** [ben/foundry-ironsworn#21]
Thanks so much for this module, my little co-op group was shocked how well it worked. Having the move reference right on the character sheet is great.

Issue we found is that most oracle rolls worked great, but the choice ones (likely, unlikely, etc) at the bottom don't do anything. I'm planning to make my own tables for that, but thought you might want to know they're broken.

**Comment by ben** [comment]
I'm so glad it worked for you! Thanks for the tip, I'll fix it soon.

**Comment by ben** [comment]
Should be fixed now. The newest version requires Foundry 0.8.5, but if you update your system it should be fine. Let me know if it's still broken!
