### ISSUE TITLE
Bond Track: not reacting to ticks?

### ISSUE THREAD

**Issue by funkybrain** [ben/foundry-ironsworn#23]
This may be my ignorance on how the sheet works, but I canot seem to advance the bond tack at all. Any click in the checkboxes remains unresponsive. I am on Foundry 0.7.9 and Ironsworn system 0.2.5 (I cannot update since apparently I need Foundry 0.8.x which is still in beta and I always stay on the released/stable version)

**Comment by ben** [comment]
To advance the bonds track, click the little pencil-and-paper icon on the right end of the track. There you can add a bond, which has a name and some notes. 

Sorry it's not very discoverable. What would have helped you find it?

**Comment by funkybrain** [comment]
My apologies - I was speaking out of ignorance of how that track works. I thought it was a clickable track like most progress tracks, but now I understand it gets auto-advanced every time you add a bond. I did find the edit button and added 3 starting bonds but because progess is slow I did not make the connection that it was progressing that track :/ All good, and thanks for all the work you do.
