### ISSUE TITLE
Logging Posts Multiple Times To Log

### ISSUE THREAD

**Issue by SasugaTV** [ben/foundry-ironsworn#233]
When the logging happens, sometimes it posts to the chat once for each person in the game (or possibly for each GM or Assistant GM).

When something is added or deleted from the party sheet, it will state it once per person.

It was doing it three times, and now that we have a fourth player it's posting things four times.

![image](https://user-images.githubusercontent.com/38813948/158500170-cbce77ef-3612-4bb4-8c67-0ba7b4eb622c.png)

**Comment by ben** [comment]
Ooh good one! I've got a fix, I'll make sure it goes out today.

**Comment by ben** [comment]
Shipped a fix with 1.10.25 just now!

**Comment by SasugaTV** [comment]
Hi, so this is still happening (or happening again) when deleting things.

It's not doing it for everything anymore, so it's fixed in some places, but it's definitely still doing it for deleting things from the party sheet, and possibly in other places.
