### ISSUE TITLE
[Incentivized Feature Request] Foes as Tokens / Actors

### ISSUE THREAD

**Issue by bunnysage** [ben/foundry-ironsworn#238]
## The Why
As an enthusiast of the maps & minis approach, I would like to represent foes within scenes as tokens. I imagine there will be a decent % of users who feel the same way.

## The Feature
I’d like an actor type “NPC” that works just like the Foe items that can be added to character or shared sheets.
It would have the same fields as the Progress item type, but be an actor.

<img width="521" alt="bladewing" src="https://user-images.githubusercontent.com/86330532/158851023-3dc61f8b-8129-4a16-b238-fb53e2cdc18c.png">

I could also see the NPC actor being a “wrapper” over a Progress item to avoid duplication of data / functionality. I’ll defer implementation details to someone more knowledgeable than me.

I would like for the token to be not tied to the actor data if possible, so you can create multiple independent copies by default when dragging the actor onto a scene.

> Side note: One thing I’ve noticed in IS as opposed to other frameworks is updating data in the character sheet does not update the linked token data (such as name or image), but I don’t know enough about the framework yet to comment

## Incentivization
I believe in incentivizing open source development. I'd like to offer $400 for the feature as described or as implemented in a more clever way that I’m not aware of, payable on delivery.

> @ben if you prefer to keep this off your repo I’m happy to re-work as a standard feature request.

When working with contractors (a relationship I’m on both sides of) I believe in milestone-based deliverables to build trust among the parties

However in this case the milestone is so small I think it makes sense to do a single payout.

Payable in various cryptos or USD over PayPal, etc..

**Comment by ben** [comment]
Going to do this over in #252. If it's alright with you, go ahead and send that money to [Razom](https://razomforukraine.org/razom-emergency-response/). I'll update here when the feature has shipped so you can try it out.

**Comment by ben** [comment]
Shipped as part of 1.10.30. There's now an actor compendium for foes, which you can drop onto the map, and their sheet shows a minimal view of options for the contained progress item.

![CleanShot 2022-03-27 at 07 23 01](https://user-images.githubusercontent.com/39902/160286064-61693eb6-71b4-4876-a51b-32cbbf30229f.jpg)

**Comment by bunnysage** [comment]
I ended up implementing this on my own branch

**Comment by bunnysage** [comment]
Hey Ben, sounds great - I'll grab the latest version and try it out.

Posting an anonymized reciept of Razom as the donation recipient for posterity.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/86330532/160728182-e9c679a6-efc2-4bf6-ad0a-052e3a6a0b45.png">

**Comment by bunnysage** [comment]
I did attempt this on my own branch (though yours is much better). it was a good exercise to get a bit more familiar with foundry dev and your codebase.

**Comment by ben** [comment]
Glad you're happy. Thanks for the donation to Razom!
