### ISSUE TITLE
Version Requirement is 8.3?

### ISSUE THREAD

**Issue by lwd-hollis** [ben/foundry-ironsworn#25]
The files are currently requiring version 8.3, so this is not usable by anyone on the Release (Stable) update channel

**Comment by ben** [comment]
Yeah it's possible I jumped the gun there. Version 0.2.5 works with Foundry 0.7.x, just use [this manifest URL](https://raw.githubusercontent.com/ben/foundry-ironsworn/0.2.5/system.json).

Foundry 0.8.x stable should be out tomorrow, so hopefully this won't affect people for much longer. Sorry for the difficulty, this is an awkward period.
