### ISSUE TITLE
markdown move text rendered as plain text in chat log

### ISSUE THREAD

**Issue by rsek** [ben/foundry-ironsworn#258]
specifically the complete move text that's output by clicking the move's entry in the move list. other methods may suffer from this too, i just didn't look especially closely at the time; it may crop up in certain oracle results as well (particularly Move Oracles, many of which feature links in them)

related: some of Dataforged's internal typings use an `MdString` type; it's just a wrapper around a bog-standard string that exists to hint which things are supposed to be parsed as Markdown. with vanilla TS that's not especially useful, but with something like `typescript-is` it could be leveraged to determine what should be parsed into HTML when building `foundry-ironsworn`'s data from Dataforged.

currently not everything that uses markdown is properly hinted in this way, but i could bump it to the top of Dataforged's TODO if it'd be useful to you. and, if adding a whole-ass runtime typing library to the devdeps isn't feasible (and, i mean, fair enough ;) ), another possibility would be a directory/branch of dataforged with the HTML already rendered (yet another thing on Dataforged's TODO).

**Comment by ben** [comment]
Should be fixed now.
