### ISSUE TITLE
Logging Posts Multiple Times To Log #233 Still Happening Or Happening Again...

### ISSUE THREAD

**Issue by SasugaTV** [ben/foundry-ironsworn#298]
So, when deleting creatures/progress from the party sheet, it's still logging multiple times (based on the number of people on the server at the time).

It's not happening with everything, like before, but it is still happening with some things, particularly deleting progress/creatures from thee party sheet.

**Comment by ben** [comment]
Found the bug, I'll ship a fix in a bit. Thanks!

**Comment by ben** [comment]
Shipped with 1.10.45. Let me know if it breaks again!
