### ISSUE TITLE
Manifest or files don't work

### ISSUE THREAD

**Issue by WallaceMcGregor** [ben/foundry-ironsworn#3]
Hi

I'm glad to see an Irosworn system (thank you so much), but the manifest url didn't work. I also tried to download all files and put it on the system folder an didnt' work.

![FoundryVTT_2020-12-16_05-54-22](https://user-images.githubusercontent.com/17795541/102306806-6395b580-3f63-11eb-913d-0e660044ae5f.jpg)

PD: When it works, I plan to translate it into Spanish.

**Comment by ben** [comment]
Just pushed a change, and it seems to work for me. Is that better?

**Comment by WallaceMcGregor** [comment]
Yes, now it's working. Thanks.
