### ISSUE TITLE
Oracle extensibility

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#304]
@DiceT's system has a cool feature where the oracles are organized into folders, and if you drop more tables into those folders, the oracle-rolling mechanism will randomly choose from them when it rolls, so you can make your "Action" oracle have more results.

That sounds awesome, so let's think about how to do it.

## Extending oracles with more rows

Currently, each "leaf" node in the oracle tree corresponds to a Dataforged oracle, and the content is fetched from a Foundry RollTable. This would be extended to look for tables in directories that match the location of the oracle in the tree. So if a roll table is in "Oracles/Creatures" and is named "Environment", it would extend the core Creatures/Environment oracle with more results.

For tables in compendia this is trickier, because there's no directory structure. Maybe we can use the description field for this; if we find something like `[[Oracles/Creatures/Environment]]` in there, we can treat that as its location in the tree. We'd walk all compendia at init time and make a note of tables that should add content.

## Adding new oracles

Since we're using "Oracles" as the root, there's no reason we can't add more items to the tree that way. The new tree branches and leafs won't have any descriptions to them, but they can be inserted into the tree that starts with Dataforged. We'd want a hook that watches for tables being created/updated/deleted and re-generates the tree.

Same with compendia if we're using the technique listed above. `[[Oracles/Tech/Blasters]]` would create a new branch and a new leaf. For descriptive text, since there's no Dataforged content here to use by default, we'd fall back to the first table description we run across that has any content.

## Building the tree: an algorithm

1. Make a copy of the Dataforged `oracles` tree, and add `Tables` arrays for Foundry IDs
2. Walk the rolltable directory structure, adding to the tree using the current location in the folders for the tree location
3. Iterate through table compendia, adding to the tree using text that matches `[[Oracles/...]]` in the table descriptions for the tree location

Adding to the tree looks like this:

1. Walk the oracle tree along "path" of this addition
2. If any of the "branch" nodes do not exist, insert `IOracleCategory` objects for them
3. If this leaf node does not exist, create it
4. Add this table to the list of Foundry table IDs

## Rolling on tables

@DiceT's system does the [simplest thing](https://github.com/DiceT/starforged/blob/master/modules/generators/core-generator.mjs#L5), which is to randomly choose a table that matches the intent, and have Foundry roll on it. That's probably a good place to start, but it may introduce weighting issues: if table A has 100 entries on it, and table B has only 2, B's results have 50x the weight of A's. 

But the "better" solution is really tricky, and involves some potentially hairy dice math. If A's results are all one number on a d100, and B's are one number on a d20, we have to normalize to the biggest die and construct a supertable with all the results. I'd like to preserve the nice dice-so-nice rolling experience, so if at all possible we should avoid things like a d127.

So the first version of this will trust the user to know how the weights are going to work, and trust the norms of the system that have all oracle tables rolling a d100. It might be enough.

## I18n

Supporting multiple languages makes this more complicated. If Foundry is running in Spanish, and I have a Babele module that provides Spanish translations for the core oracles, what happens if I pull in another module that adds tables, but all the names are in English?

That's obviously a corner case that we can't do anything about, but we _can_ make it possible to extend the oracles if everything is in Spanish. The strategy looks like this:

* The UI tree is built using localized names, so to extend the Action oracle we'll look in the `Oráculos/Oráculos Centrales/Acción` folder, and match against `[[Oráculos/Oráculos Centrales/Acción]]` in compendium table descriptions.
* Descriptions and table results will come directly from roll tables, so that [Babele](https://foundryvtt.com/packages/babele/) can provide translations for the built-in tables, and new oracles will have their native content.

**Comment by ben** [comment]
Another thought: this could all be implemented by an `oracleTree` hook that runs after copying the Dataforged tree and importing content from roll-tables, but before displaying the tree in the UI. That would give lots of flexibility for modules to augment and/or replace parts of the tree themselves, and would shift a lot of this complexity out of the core system.

**Comment by ben** [comment]
A third way: 

1. Create a RollTable folder called "Custom Oracles" (i18n), and any tables in that folder are included in a "Custom" (i18n) node in the oracle tree
1. _Also_ send out a hook so that modules can augment the tree, which runs _after_ step 1.

**Comment by ben** [comment]
Looks like this is done as of #333. We've got the tree structure, we've got the folder, we've got the hook. 🎉

**Comment by DiceT** [comment]
I am going to be creating a module that will add a tags variable to RollTable that will contain an array of tags that will allow RollTables to be grouped by and rolled against. This will allow one RollTable to be potentially rolled on in different categories/tags.

The intent, obviously, is that this will work in any system.
