### ISSUE TITLE
Oracle results: inline table links could use some work

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#308]
These could use a readability upgrade, and it would be nice to navigate to them like we do with moves. Currently clicking just opens the roll table UI itself, which isn't great.

We could also make use of Dataforged's `Suggestions` field here to auto-link tables to roll next.

![CleanShot 2022-04-24 at 15 52 48](https://user-images.githubusercontent.com/39902/165000120-d9929cba-fa24-437a-8726-d783c4d23e8c.jpg)

**Comment by DiceT** [comment]
I always hated this. You could get around it with a Macro, but that's not necessarily the best solution.

**Comment by ben** [comment]
Now that #354 is merged, we could extend its logic to replace these links as well.
