### ISSUE TITLE
Invalid manifest

### ISSUE THREAD

**Issue by kdmcdrm** [ben/foundry-ironsworn#34]
When I try to update the system I'm getting a "URL did not provide valid manifest" error.

**Comment by ben** [comment]
Whoops! Sorry about that. I restructured the code, and the `system.json` file moved. If you uninstall and reinstall the system, you won't lose any data in your game. I'll make a note in the Foundry document.

**Comment by Bapf** [comment]
The URL in the README.md also still points to the wrong direction.

**Comment by ben** [comment]
Whooooops! Fixed!
