### ISSUE TITLE
Enhanced roll flow

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#363]
Courtesy of @rsek, a semi-complete diagram of possible roll mechanics:

![](https://cdn.discordapp.com/attachments/867434336201605160/974833534281855016/starforged_roll_operations.png)

There's a lot here we don't support.

**Comment by rsek** [comment]
some notes:
* it's probably impractical support "before rolling" without some really dense annotation from dataforged. best i can think of is, like, a checkbox so people can indicate "i've opted-in to the choice" in asset abilities that use the "before rolling" language
* arbitrary dice rolls are probably handled fine by the default `/roll` command, though it might be nice to add a shortcut somewhere
* "Count [outcome] as [outcome]" is something i annotate for in dataforged in assets; it's something i'd *like* to add to some default moves, but i'm still considering how best to approach that. might make more sense to just give the player the ability to set that manually via some sort of "edit roll" button on the chat log output

**Comment by ben** [comment]
Another note: let's put in a bit of effort trying to find the right "speaker" for the roll in the chat window. If the roll is coming from a move sheet, it should belong to that actor; if it's coming from a shared sheet, the answer is also pretty easy. What if it's a progress roll on an NPC sheet? Not sure, but let's at least try.

**Comment by rsek** [comment]
pre-setting challenge dice isnt in, is it? should i open a separate issue for that?

**Comment by ben** [comment]
Ooh, yeah. Looks like we missed that part. Shouldn't be too hard to add at this point, though.
