### ISSUE TITLE
Location actor Region is reset to "Terminus" when closing sheet

### ISSUE THREAD

**Issue by boostedPeaks** [ben/foundry-ironsworn#376]
When opening the sheet for a location-type actor, the Region is being reset to "Terminus," regardless of what I had it set to.

![image](https://user-images.githubusercontent.com/104098609/170846203-01257d24-90c7-4183-a49d-9380d3cc49ff.png)

Foundry 9.269, system 1.15.11

**Comment by ben** [comment]
OK yeah, this isn't actually stored on the actor, it's stored on the scene. This is confusing, because why is there a control here unless the field gets saved?

I'll have to think about how to represent this in a way that's easy to find.

**Comment by ben** [comment]
I just pushed a change that makes it so that setting this on a location persists it at the sector level. It'll go out with the next release.
