### ISSUE TITLE
v10 migration

### ISSUE THREAD

**Issue by rsek** [ben/foundry-ironsworn#384]
might be a bit early to start, but i imagine it'll have to happen at some point, so i'll write it down here :)

the v10 API docs: https://foundryvtt.com/api/v10/
this issue tracks the breaking changes to the data model: https://gitlab.com/foundrynet/foundryvtt/-/issues/6849

one item of note from the replies:
<img width="340" alt="Screen Shot 2022-06-08 at 10 47 08 PM" src="https://user-images.githubusercontent.com/5354757/172773483-5303b302-54c6-4285-9975-eab9b31504f1.png">

my understanding is that this is true for all Documents.

**Comment by ben** [comment]
Closing this in favor of #385.
