### ISSUE TITLE
Foundry v10 Compability

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#385]
This issue collects things that are broken. Leave a comment if you find something.

Notes grabbed from #384:
- the v10 API docs: https://foundryvtt.com/api/v10/
- this issue tracks the breaking changes to the data model: https://github.com/foundryvtt/foundryvtt/issues/6849

## Bugs to fix
- [x] Canvas buttons don't work
- [x] Clicking a move link in an asset doesn't navigate in the move sheet, it opens the move-edit sheet.
- [x] Migrated warnings to #526

**Comment by rsek** [comment]
as of today, FVTT has (apparently) migrated their issue tracking to github. the breaking changes to the data model are now being tracked here: https://github.com/foundryvtt/foundryvtt/issues/6849

what are the prospects for the version difference? like, is maintaining compatibility with both v9 and v10 likely to be difficult? what tools does Foundry provide to assist that? what sort of timeline are you looking at for dropping support with v9?

also, if you think it's worth opening a v10 branch, i could start knocking out the low-hanging fruit for the `Foo#data` => `Foo#system` transition.

**Comment by ben** [comment]
> as of today, FVTT has (apparently) migrated their issue tracking to github. the breaking changes to the data model are now being tracked here: [foundryvtt/foundryvtt#6849](https://github.com/foundryvtt/foundryvtt/issues/6849)

Updated the link, thanks.

> what are the prospects for the version difference? is maintaining compatibility with both v9 and v10 likely to be difficult? what tools does Foundry provide to assist that? what sort of timeline are you looking at for dropping support with v9?

I hadn't thought about it too much. I'm hoping they'll back port some compatibility things (i.e. using `item.system` instead of `item.data.data`), and that will enable us to work in v10 primarily, and still preserve some v9 compatibility. But if we go whole-hog on the journal things, probably we'll just make a clean cut; working on two systems in parallel is probably more than this little project can bear.

> also, if you think it's worth opening a v10 branch, i could start knocking out some low-hanging fruit.

Possibly? For now let's see if we can fix some v10 issues while maintaining v9 compatibility. Long-running branches end up becoming problems rather than solutions IME.
