### ISSUE TITLE
Small conflict with DF Manual Rolls

### ISSUE THREAD

**Issue by chaoscontrolled123** [ben/foundry-ironsworn#411]
DF Manual Rolls has been working great with Ironsworn so far, but yesterday I enabled "flag manual rolls" on a whim and suddenly rolls stopped appearing in the chat! I found this error in the console:

![image](https://user-images.githubusercontent.com/14331415/180626228-9ac6efb8-d9fd-4b59-8ad5-5d9f3177d052.png)

I only know a teeny bit of javascript, but I'm guessing that means this module is sending the manual roll flag in such a way that the Ironsworn system thinks it's an extra die roll? If I disable "flag manual rolls," the messages start appearing correctly again. I'm posting this here since it hasn't been an issue with the other game system I tried (PF2e) but if it's something that needs to be fixed on DF Manual Rolls' end, I'll report it there.

(I play a very NPC and dialogue-heavy game with my friend, and this system has been a lifesaver! Thanks for all your hard work! 😊)

**Comment by ben** [comment]
Okay, I found the bug. Part of the logic we do on a roll is to see if negative momentum would cancel an action die, so we pre-calculate the result if that were the case. The code that was doing that was receiving an input like `'d6[[MR]] + 2'`, and replacing the `d6` part with `0`. We then send `0[[MR]] + 2` to Foundry for resolution, and it doesn't like that at all, and you get the error message you discovered

I've just shipped 1.16.1, which should prevent this error message, but unfortunately the way we generate the chat-message HTML, it doesn't look like manual rolls will be visually tagged as such, so this particular corner of DF Manual Rolls just isn't going to work. I've filed #412 to track that, maybe someday we'll get around to fixing it. Thanks for the report!
