### ISSUE TITLE
Assets, Delve, Foes translation

### ISSUE THREAD

**Issue by Potatronus** [ben/foundry-ironsworn#428]
I would like to translate whole ironsworn module Englishglish to polish. Already translated 50% of json in lang/Ibut i don't see the option to translate the assets and the other stuff. Anyone can help me?

**Comment by ben** [comment]
The best way to do this would be to make a [Babele](https://gitlab.com/riccisi/foundryvtt-babele) module which replaces the contents of the built-in compendium items. Target the `foundry-ironsworn.ironswornmoves` (which will be official soon) and `foundry-ironsworn.ironswornassets` (official now) compendiums for Ironsworn content.

**Comment by ben** [comment]
Oh, and I'd <3 a PR that adds Polish translations. Take a look at #14 to see what kinds of change you'll need to make to system.json.

**Comment by Potatronus** [comment]
I'm not the IT guy, to be honest, just created this account to work on translation :).
At this moment I'm working with descriptors used in foundry-ironsworn/lang/*.json which work with descriptors, general descriptors used in-game, delves and some tables.

I also added in system.json
{
lang": "pl",
      "name": "Polski",
      "path": "lang/pl.json"
}
The data I have in English I can properly translate.  At this moment I translated it is still early state. But there is no descriptors for assets in lang/.en.json to translate ;)

![image](https://user-images.githubusercontent.com/111095274/184458034-3f60bd39-85bf-47cd-925d-e19326bd00ab.png)

**Comment by ben** [comment]
That's great! Can you post the `pl.json` file somewhere I can download it, and I'll make a PR to integrate it?

**Comment by Potatronus** [comment]
> That's great! Can you post the `pl.json` file somewhere I can download it, and I'll make a PR to integrate it?

Hey, sure. I didn't have a chance to finished whole translation yet, but still I can upload a json. I don't know how to upload it @ github (tried to use a pull request and add a file AND the code change, but afaik it didn't work), so i will just give you a link to drive with pl.json

https://drive.google.com/drive/folders/1ySdbPch5N4E0Eo6ncdN2cwohsT4Ums8y?usp=sharing

**Comment by ben** [comment]
Got it! You should now be able to navigate to [this file](https://github.com/ben/foundry-ironsworn/blob/main/system/lang/pl.json) and hit the edit button to submit a pull request. This initial version will ship with the next release. Thanks!
