### ISSUE TITLE
Ironsmith content

### ISSUE THREAD

**Issue by Potatronus** [ben/foundry-ironsworn#429]
Is it possible to add the move from unofficial - Ironsmith content?
https://www.drivethrurpg.com/product/351813/Ironsmith

**Comment by ben** [comment]
The only things I can include in the system are things that are licensed for completely free distribution, which mostly means the mechanics (and not full content) of the official books.

I'd love to see this as a premium Foundry package, where Eric Bright gets some monetary benefit from it, but I'm not sure how to get from here to there. Is this something you'd be interested in pursuing?

**Comment by Potatronus** [comment]
To be honest I didn't think about that. I bought Eric's package from DTRPG for a few $ and I totally forget we can use only free content in the foundry (i just installed the foundry 2 weeks ago ^^"). So yeah probably that was a bad idea, but if Eric would get some extra $ for his work that would be nice :).

**Comment by rsek** [comment]
regardless of whether it'd need to be paid content or not, it's probably be wise to make any 3rd party content a separate module that's dependent on this system... though, hm, might function well as a system-agnostic module if it were the oracles.

(TBH, i wouldn't mind seeing more modularity between the classic/delve/starforged content, either, but that should probably have its own issue)

**Comment by ben** [comment]
> i wouldn't mind seeing more modularity between the classic/delve/starforged content

This is a tricky one, because when you download a system, you'd expect it to be playable right then. It'd feel bad to spin up a new world, drop in and get the "Oh hai you need to go back to setup mode and install one of these three things to actually play". This can get a little fuzzy with defining dependencies, but if all your dependencies are always installed, they come from the same authors, and their content isn't really usable in any other system, why are they separate?

Delve I could see an argument for, as well as Sundered Isles when it comes out. But core Ironsworn/Starforged content should probably still be in the core system.

**Comment by rsek** [comment]
> Delve I could see an argument for, as well as Sundered Isles when it comes out. But core Ironsworn/Starforged content should probably still be in the core system.

yeah, fair. i think there may be a benefit for system-agnostic bits in particular: specifically, the oracles. they could live in their own modules, then be pulled in as system dependencies; for folks using the IS system, that'd be pretty close for to the current experience. but it'd provide an option for folks who want to use the IS/SF oracles with a different system.

i reckon that in an ideal world, getting optional game content would just be part of a guided setup experience, where a user is prompted with something like: "Which oracles do you wish to install?". or FVTT itself would have some handling of optional dependencies that prompts people with the option of installing them.

i don't think either of those is really feasible at the moment, but maybe some day. ;)

**Comment by ben** [comment]
Going to close this for now, since I think we answered the specific question.
