### ISSUE TITLE
Assets return "undefined" after edit

### ISSUE THREAD

**Issue by Aritei** [ben/foundry-ironsworn#43]
When opening an asset as an edit and selecting anything, some (not all) assets change all effects to "undefined". Examples we discovered was the Veteran, Blade-Bound and Wayfinder asset.

**Comment by acrologic** [comment]
I have this issue as well, it appears to be the case when editing any asset.

**Comment by ben** [comment]
Found the cause, I'll ship a fix in a bit.

**Comment by ben** [comment]
Just published 0.4.4, which should fix this. Let me know if you have any other issues!
