### ISSUE TITLE
Character sheet v2 doesn't display Momentum Max/Reset values

### ISSUE THREAD

**Issue by japatsu** [ben/foundry-ironsworn#430]
See image. 

For a new character, there are blank values for Momentum Reset/Max with v2 sheet. With classic sheet Reset/Max have values (2/10).

![image](https://user-images.githubusercontent.com/61741172/184446326-a58d4bcf-9396-4791-a002-eedd23aaa42b.png)

**Comment by ben** [comment]
Ha, turns out these numbers aren't in the template.

**Comment by ben** [comment]
Fixed inaccd78b646d58c1670806fa4d8013e9a2206f6bc, this will go out in the next release. In the meantime, set then clear a condition, and that'll make sure these numbers appear. Thanks!
