### ISSUE TITLE
Truths: Random selection at category and suboption level

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#431]
The current implementation requires manual selection of all truth categories and sub-options. But the book includes rolling values for randomizing.

This probably requires restructuring of the components to make this more tenable. The current system is kind of fragile and tightly-coupled, and hard to make work properly.

**Comment by rsek** [comment]
i could imagine truths presented as something like a step-by-step "setup wizard" experience. while this isn't a tour/tutorial _per se_, i wonder if there's anything that v10's Tour API could offer here?
