### ISSUE TITLE
Negative momentum not being subtracted from rolls currently

### ISSUE THREAD

**Issue by jcsanady** [ben/foundry-ironsworn#434]
When the action die matches your negative momentum the system outputs the line "Negative momentum canceled action die" but then proceeds to complete the calculations without subtracting the die.

![Momentum Bug](https://user-images.githubusercontent.com/11475872/185623095-2522ef19-19f5-45c4-af36-d368cf17fe90.png)

**Comment by ben** [comment]
This will be fixed with #422.

**Comment by ben** [comment]
Proof by screenshot:

![CleanShot 2022-08-19 at 11 51 42](https://user-images.githubusercontent.com/39902/185687442-0296872f-f7e2-4563-a04d-7356d9d97775.jpg)

**Comment by jcsanady** [comment]
Good to know, thanks!  And thanks for the awesome work on the system.
