### ISSUE TITLE
suggestion for starforged sheet improvement

### ISSUE THREAD

**Issue by gothalo** [ben/foundry-ironsworn#44]
It's not an issue but a suggestion. Could it be possible to increase contrast in the momentum, health, spirit and supply markers of the new starforged sheet? Currently it's hard to see what is the current value of them.

thank you very much.

**Comment by ben** [comment]
Started #44. Does that look better?

**Comment by gothalo** [comment]
Yeah! It's much better

**Comment by ben** [comment]
Merged and shipped. Update to 0.4.5 to see it. Thanks!
