### ISSUE TITLE
Chat-Card CSS(?) is not aligned properly

### ISSUE THREAD

**Issue by tagnullde** [ben/foundry-ironsworn#445]
When rolling a Site-Feature the CSS of the Chat-card is off. Might happen on other rolls too. Haven't checked all the possibilities.

![image](https://user-images.githubusercontent.com/44159008/186455394-0b01ee88-059a-4dcd-9668-d6d3bef15327.png)

**Comment by ben** [comment]
Nice catch! I'll remove the CSS class for now until we can update this with the SF table-draw look and feel.

**Comment by ben** [comment]
Shipped a temporary fix with 1.17.1. Thanks again!

**Comment by tagnullde** [comment]
You are welcome. :)
Thanks for making this system.
