### ISSUE TITLE
Delve moves refresh

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#456]
Some of the Delve moves don't fit into the new move/oracle framework very easily:

* _Delve the Depths_ has you roll a stat, and on a weak hit you roll a d100 on a table column depending on the stat you rolled.
* _Reveal a Danger_ is like an oracle roll, but 1-45 results consult the theme/domain instead of a fixed table. There's also an alternate version that doesn't use theme/domain at all.
* _Find an Opportunity_ has a fixed table, but if you're coming from another move, you can choose your result. Then there's also a secondary effect that you choose.

The standard move/oracle rolling code doesn't quite support these flows, so until we can replicate this stuff, I'll have to leave the old `RollDialog` in place.

**Comment by rsek** [comment]
hmm. is there anything i could add to `dataforged@next` that make this easier? in the past i've considered embedding the roll-this-table-for-this-stat info in `IMoveTrigger` -- but explicitly stat-sensitive outcomes are fairly rare in IS/SF, so it didn't seem worth it at the time.

an alternative to that would be enumerating Delve the Depths as 3 separate moves -- maybe not in dataforged itself, but instead generated at build time from DF's single DtD move. so, there'd be the Edge, Wits, and Shadow versions, each with a single stat trigger option, and each would have different oracle suggestion associated with it.

that'd still require some additional scaffolding to handle the whole DtD "lifecycle" smoothly (not to mention the other moves), but it might allow it to borrow from the existing templates.

**Comment by ben** [comment]
At this point it seems like a pattern that Shawn has left behind, so I don't think it needs a ton of framework or data-model support. I'm comfortable letting these have their own specialized implementation, because it doesn't seem like we'll be seeing this sort of thing again in the near future.

**Comment by rsek** [comment]
> At this point it seems like a pattern that Shawn has left behind, so I don't think it needs a ton of framework or data-model support. I'm comfortable letting these have their own specialized implementation, because it doesn't seem like we'll be seeing this sort of thing again in the near future.

seems sensible -- i get the same impression re: that particular game design pattern.

DF's ironsworn preview data (soon to be the new datasworn, #459) now includes delve site theme/domain data. they're formatted pretty much exactly as "partial" oracle tables, such that you could do something like

```typescript
const delveFeatures = theme.Features.concat(domain.Features)
```

and have a complete DF-style oracle table ready to go. Dangers are slightly trickier due to Reveal a Danger, but even then you'd only have to remove the "Check the theme card" and "Check the domain card" rows before concatting the card Dangers.

**Comment by ben** [comment]
I'm going to call this done. We've bent our nice, general system to accommodate these weird moves enough, and it's now possible to do what they tell you to do.
