### ISSUE TITLE
Dataforged/Datasworn 2.0 migration

### ISSUE THREAD

**Issue by rsek** [ben/foundry-ironsworn#459]
currently this is on `dataforged@next` on NPM. it has some breaking changes, [detailed here](https://github.com/rsek/dataforged/blob/main/CHANGELOG.md). if there's any further breaking changes you want to suggest, lemme know and i'll see if i can sneak it in.

it also includes the Ironsworn region entries, encounters, and world truths. if it passes muster, that will become the new Datasworn NPM package.

heads up, there's a lot of not-quite-canonical MD link annotations in the IS region and encounter entries (my strategy was basically to treat it like marking up a wiki article). they're quite serviceable if these are simply stripped out, but part of the reason i decided to include them is that i figure a platform like FVTT can get a lot out of pointers to other articles.

the downside might be that it makes the prose a bit obnoxious to read due to the current formatting (at least in v9 -- i'm not familiar with how v10 handles links in the prosemirror editor off the top of my head?) being a minor break in the 'flow' of the text (since its styled as a button). that might be addressed with some restyling on the relevant sheet, though.

**Comment by ben** [comment]
Took a couple of swings, but it's done, at least for DF2 v0.1.0-0.
