### ISSUE TITLE
Actors from wayyy back sometimes have strings where there should be numbers

### ISSUE THREAD

**Issue by orffen** [ben/foundry-ironsworn#460]
I have an issue where almost every move results in a strong hit - you can see here that only the Make Camp move had the correct action score calculation:
![image](https://user-images.githubusercontent.com/2225985/188787657-6da0095f-c826-4578-a28a-51ecdbea7c95.png)

I've updated to Foundry v10 and the module is 1.17.5. The issue occurs without any additional modules loaded.

**Comment by ben** [comment]
That's odd. Can you do me a favor and get some data from one of those chat messages? Here's how:

1. Open up Foundry in a Chrome browser
2. Hit ctrl+shift+c (or cmd+shift+c on a mac)
3. Click on the move name in one of the faulty messages
4. In the element inspector that comes up, scroll up a bit and copy-paste everything in the `data-ironswornroll` property that should be easy to find.

Here's what you're looking for:

![CleanShot 2022-09-07 at 09 24 16](https://user-images.githubusercontent.com/39902/188930776-1553df17-be94-4df9-b4ee-094c9b93e2c3.jpg)

**Comment by orffen** [comment]
Here you go:
```
<article class="ironsworn-roll flexcol" data-ironswornroll="{
  "preRollOptions": {
    "moveDfId": "Ironsworn/Moves/Adventure/Secure_an_Advantage",
    "actorId": "uWvENTn10SKScdxe",
    "momentum": 1,
    "stat": {
      "source": "shadow",
      "value": "2"
    },
    "adds": 1
  },
  "postRollOptions": {},
  "rawActionDieValue": 5,
  "rawChallengeDiceValues": [
    5,
    10
  ]
}">
```
All of the data looks right to me - I see a 5 on the roll, +2 shadow, +1 adds.

But action score says 10:
![image](https://user-images.githubusercontent.com/2225985/188998940-20f4803e-d8f0-46aa-9411-7c5af8aa88a2.png)

**Comment by ben** [comment]
You're right, everything in there looks just fine. It's really just the circled "10" that's wrong here. The outcome is interpreted correctly as a weak hit. It's so weird, I can't replicate this at all. Can you tell me which browser you're using, what OS, any modules that might muck with the dice rolls, anything like that?

**Comment by orffen** [comment]
In this one it's a weak hit because a challenge die was 10 (and the roll would have to beat it to be a strong hit) but it is interpreting it as strong hits whenever there isn't a 10 on either of the challenge dice.

I double-checked that my `ironsworn.js` wasn't different from the one in the latest release but they are identical (just in case).

There are a couple of console messages which are being logged and I can see in the `renderRollGraphic roll` output that score has been set to 10:
![image](https://user-images.githubusercontent.com/2225985/189001666-44c94e60-6fcb-400c-b986-a64d0ab8498f.png)

The getter for `IronswornRoll.score` seems to be returning the minimum of `this.rawScore` and SCORE_MAX which is 10, and so is returning 10.

`rawScore` is a bit complex but appears to return either a sum of all terms that aren't undefined ('void 0'), or undefined. It's not returning undefined (if it did score would be undefined instead of 10), but it appears it's returning >10. 

I suspect something is happening here:
```
    terms.push((_a = this.preRollOptions.adds) != null ? _a : 0);
    if (terms.every((x) => x !== void 0)) {
      return lodash$2.exports.sum(terms);
    }
```

This *should* just sum all terms that are undefined, but I suspect it's doing something funky and so getting a result greater than 10.

**Comment by orffen** [comment]
I've just noticed something else, if I select a predetermined action die outcome it automatically shows 10:
![image](https://user-images.githubusercontent.com/2225985/189008150-09d1bae1-fa44-4128-97b6-2ee15e961034.png)

If I set a negative value in the predetermined dialogue I get this strange output, and the value in the field shows as -330:
![image](https://user-images.githubusercontent.com/2225985/189008536-83c8fce9-c73b-4579-bef2-f13e040119a4.png)
`<span class="score" title="">-330</span>`

I think it's something with these old characters. The world was created I think way back in v8, there may have been issues with data migration between FoundryVTT and the system versions. A new character doesn't have the issue.

**Comment by orffen** [comment]
Argh - I've found the issue. The old characters have strings in their stats:
```
    "edge": "2",
    "heart": "3",
    "iron": "2",
    "shadow": "1",
    "wits": "1",
```
While the new characters have numbers:
```
    "edge": 1,
    "heart": 1,
    "iron": 1,
    "shadow": 1,
    "wits": 1,
```

Not sure if this happened during a data migration but I wouldn't be surprised.

**Comment by orffen** [comment]
It may be worth adding some `parseInt` code in places where this could happen, but my fix is to edit the affected sheets, bump a stat +1 and back down -1. When it updates it convert it to an int and rolls are looking good now.

**Comment by ben** [comment]
Oh wow! Nice debugging work!

I don't think it's worth adding `parseInt` calls in _every_ place we reference stats (which is quite a few), but if someone mentions this again now I know what to tell them. Ready to close the issue?

**Comment by rsek** [comment]
> I don't think it's worth adding `parseInt` calls in _every_ place we reference stats (which is quite a few), but if someone mentions this again now I know what to tell them.

hmm. reckon it'd be feasible to build it into the migration framework? then it's only gotta happen once, right?

**Comment by ben** [comment]
Yeah, maybe you're right. I'll leave this open and re-title it.
