### ISSUE TITLE
Reveal A Danger in Ironsworn/Delve produces lost article.

### ISSUE THREAD

**Issue by Rooksgate** [ben/foundry-ironsworn#461]
Hey ho. A lost page in Ironsworn/Delve.

![image](https://user-images.githubusercontent.com/78949799/189058723-c64a21f0-f204-434c-b719-b7c87105bfb4.png)

produces: 

![image](https://user-images.githubusercontent.com/78949799/189058810-3c0fd94c-8d25-49ed-af5e-638fb1a4a3c0.png)

**Comment by rsek** [comment]
huh.  🤔  so is the culprit there is the initial forward slash breaking a regex for links at build time? not sure where it'd be coming from -- the links appear to be formatted correctly in dataforged:

<img width="751" alt="Screen Shot 2022-09-08 at 5 56 11 AM" src="https://user-images.githubusercontent.com/5354757/189127356-938b242f-f0c8-4366-8863-de8e098c9430.png">

come to think of it -- not a ton of move links in oracles, are they just not being stripped/formatted in the first place?

**Comment by rsek** [comment]
> come to think of it -- not a ton of move links in oracles, are they just not being stripped/formatted in the first place?
actually, yeah, i'm pretty sure this is it -- forward slash doesnt even gotta come into it. totally forgot that FVTT parses markdown in chat messages, so it's looking for a directory that's relative to the FVTT host server. plus its not getting the FVTT item link styling.

there's a handful of oracles aside from Reveal a Danger's that include move links iirc. most prominent instances are the "you hit 0 and something bad happens" oracles embedded in Endure Harm and Endure Stress.  but they're not *super* common, so maybe these guys just fell thru the cracks

**Comment by ben** [comment]
I found it. In the [Starforged importer](https://github.com/ben/foundry-ironsworn/blob/30d5584a7942e2cce441071ec0a7e56d4cedb2af/src/module/dataforged.ts#L375) we render the links into Foundry links, but in the [Ironsworn importer](https://github.com/ben/foundry-ironsworn/blob/30d5584a7942e2cce441071ec0a7e56d4cedb2af/src/module/datasworn.ts#L331) we don't. Fix inbound.
