### ISSUE TITLE
Oracle rolls don't work and throw an error (v10)

### ISSUE THREAD

**Issue by tagnullde** [ben/foundry-ironsworn#462]
I opened the oracle tab and rolled (via the die icon) on the tables. Nothing happend, except the error in the console.

System:
![image](https://user-images.githubusercontent.com/44159008/189497963-ee6db3bd-5472-4731-932d-be22d4505bc2.png)

Error:
![image](https://user-images.githubusercontent.com/44159008/189497935-9ee34e26-5de3-4350-80de-30ed7db13e53.png)

**Comment by ben** [comment]
That's… super weird. I can't make this happen with the latest release.

Can you tell me more about your environment? Is this the Foundry app, or are you running a Chrome browser? Have you tried logging out and back in again, or going back to setup and re-starting the world?

**Comment by ben** [comment]
Also, what OS are you running? My cogs tab looks different than yours:

![CleanShot 2022-09-10 at 13 57 43](https://user-images.githubusercontent.com/39902/189501546-c572025a-6c4e-4765-9d08-9694b0cb1aa8.jpg)

**Comment by tagnullde** [comment]
Weirdly enough restarting the world did the trick and the oracle work. Should have tried that before (In my defense: It was late.*saint*).

However:
My OS is Ubuntu 22.04.1 LTS.

Using the Chrome browser and a dedicated server to run Foundry.

Active Modules:

Compendium Folders
Dice so Nice
Dice Tray
libWrapper (which causes a lot of "deprecated in v10 - no backwards compatibility when v12 hits" warnings in all systems)
Module Management+
socketLib
TableTop RPG Music

I guess this one can be closed now.
Thank you.
