### ISSUE TITLE
Can't delete invalid/old assets

### ISSUE THREAD

**Issue by Aritei** [ben/foundry-ironsworn#48]
After the last fix, assets plain can't be deleted from characters. The delete button does nothing.

**Comment by ben** [comment]
That's weird. I'm not able to reproduce that. Can you copy/paste the contents of your browser console so I can see?

**Comment by Aritei** [comment]
`​ Foundry VTT | Foundry Commons Framework Loaded
​ _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================
​ Foundry VTT | Reestablishing existing session d2e9af1ef39c5ce7099d76de
​ Foundry VTT | Connected to server socket using session d2e9af1ef39c5ce7099d76de
​ libWrapper 1.7.2.0 (ba9942f): Ready.
​ Foundry VTT | Initializing Foundry Virtual Tabletop Game
​ Ironsworn | initializing system
​ You have assigned a value to CONFIG.Actor.entityClass which should now be assigned to CONFIG.Actor.documentClass. Support for the old configuration value will be removed in 0.9.0
set @ foundry.js:53036
​ You have assigned a value to CONFIG.Item.entityClass which should now be assigned to CONFIG.Item.documentClass. Support for the old configuration value will be removed in 0.9.0
set @ foundry.js:53036
​ ColorSettings | initializing
​ libWrapper: Registered a wrapper for 'LightingLayer.prototype.animateDarkness' by module 'df-qol' with type OVERRIDE.
​ libWrapper: Registered a wrapper for 'Sidebar.prototype._render' by module 'df-scene-enhance' with type MIXED.
​ libWrapper: Registered a wrapper for 'SceneDirectory.prototype._render' by module 'df-scene-enhance' with type OVERRIDE.
​ libWrapper: Registered a wrapper for 'SettingsConfig.prototype._onClickSubmenu' by module 'colorsettings' with type OVERRIDE.
​ libWrapper: Registered a wrapper for 'DoorControl.prototype._onMouseDown' by module 'smart-doors' with type MIXED.
​ libWrapper: Registered a wrapper for 'DoorControl.prototype._onRightDown' by module 'smart-doors' with type MIXED.
​ libWrapper: Registered a wrapper for 'WallConfig.prototype._updateObject' by module 'smart-doors' with type WRAPPER.
​ libWrapper: Registered a wrapper for 'DoorControl.prototype.draw' by module 'smart-doors' with type WRAPPER.
​ libWrapper: Registered a wrapper for 'DoorControl.prototype.reposition' by module 'smart-doors' with type OVERRIDE.
​ Foundry VTT | Synchronized official game time in 6ms
​ Loaded community lighting file: /modules/CommunityLighting/lights.json
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/actor/character.hbs
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/actor/moves.hbs
​ Foundry VTT | Loaded localization file lang/en.json
​ Foundry VTT | Loaded localization file systems/foundry-ironsworn/lang/en.json
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/chat/roll.hbs
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/item/asset.hbs
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/item/bondset.hbs
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/item/move.hbs
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/item/progress.hbs
​ Foundry VTT | Retrieved and compiled template systems/foundry-ironsworn/templates/roll-dialog.hbs
​ Foundry VTT | Retrieved and compiled template modules/mmi/templates/edit-partial.html
​ Foundry VTT | Loaded localization file modules/colorsettings/lang/en.json
​ Foundry VTT | Loaded localization file modules/CommunityLighting/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/df-qol/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/df-scene-enhance/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/dice-so-nice/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/fxmaster/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/illandril-token-hud-scale/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/lib-df-hotkeys/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/LockView/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/minimal-ui/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/pings/languages/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/smart-doors/lang/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/SoundBoard/languages/en.json
foundry.js:3494 Foundry VTT | Loaded localization file modules/tidy-ui_game-settings/langs/en.json
foundry.js:2033 Foundry VTT | Rendering SceneNavigation
foundry.js:2033 Foundry VTT | Rendering Notifications
foundry.js:2033 Foundry VTT | Rendering Sidebar
foundry.js:2033 Foundry VTT | Rendering PlayerList
foundry.js:2033 Foundry VTT | Rendering Hotbar
foundry.js:2033 Foundry VTT | Rendering Pause
foundry.js:2033 Foundry VTT | Rendering SceneControls
foundry.js:4442 Foundry VTT | Document fonts loaded and ready
utils.min.js:8 
    PixiJS 6.0.4 - ✰ WebGL 2 ✰      http://www.pixijs.com/    ♥♥♥ 
foundry.js:15441 Foundry VTT | Viewing Scene Main
foundry.js:17441 Foundry VTT | Drawing game canvas for scene Main
foundry.js:10432 Foundry VTT | Constructed index of Compendium pack foundry-ironsworn.ironsworntables containing 34 entries
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/hud/navigation.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template modules/df-scene-enhance/templates/sidebar.hbs
foundry.js:2033 Foundry VTT | Rendering ActorDirectory
foundry.js:2033 Foundry VTT | Rendering ChatLog
foundry.js:2033 Foundry VTT | Rendering CombatTracker
foundry.js:2033 Foundry VTT | Rendering CompendiumDirectory
foundry.js:2033 Foundry VTT | Rendering ItemDirectory
foundry.js:2033 Foundry VTT | Rendering JournalDirectory
foundry.js:2033 Foundry VTT | Rendering PlaylistDirectory
foundry.js:2033 Foundry VTT | Rendering Settings
foundry.js:2033 Foundry VTT | Rendering RollTableDirectory
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/user/players.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/hud/hotbar.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/hud/pause.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/hud/controls.html
foundry.js:10432 Foundry VTT | Constructed index of Compendium pack foundry-ironsworn.ironswornitems containing 48 entries
foundry.js:10432 Foundry VTT | Constructed index of Compendium pack foundry-ironsworn.ironswornassets containing 78 entries
foundry.js:10432 Foundry VTT | Constructed index of Compendium pack foundry-ironsworn.ironswornscenes containing 3 entries
foundry.js:35072 Foundry VTT | Loaded Token/Thea.png (2%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/cowled.svg (4%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/aura.svg (6%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/padlock.svg (8%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/up.svg (9%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/down.svg (11%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/skull.svg (13%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/skull.svg (15%)
foundry.js:35072 Foundry VTT | Loaded Our%20Village.webp (17%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/light.svg (19%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/light-off.svg (21%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/explosion.svg (23%)
foundry.js:35072 Foundry VTT | Loaded portraits/item-large-The-Avatar-s-Shield.token.png?1623870425917 (25%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/sound.svg (26%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/sound-off.svg (28%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/door-closed-outline.svg (30%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/door-open-outline.svg (32%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/door-secret-outline.svg (34%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/door-locked-outline.svg (36%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/unconscious.svg (38%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/sleep.svg (40%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/daze.svg (42%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/falling.svg (43%)
foundry.js:35072 Foundry VTT | Loaded Revenant%201.webp (45%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/net.svg (47%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/paralysis.svg (49%)
foundry.js:35072 Foundry VTT | Loaded uploads/avatars/character/Deniz.token.png?1623870510525 (51%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/wing.svg (53%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/blind.svg (55%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/combat.svg (57%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/deaf.svg (58%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/silenced.svg (60%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/terror.svg (62%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/fire.svg (64%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/frozen.svg (66%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/lightning.svg (68%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/acid.svg (70%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/blood.svg (72%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/biohazard.svg (74%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/poison.svg (75%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/radiation.svg (77%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/regen.svg (79%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/degen.svg (81%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/upgrade.svg (83%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/downgrade.svg (85%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/target.svg (87%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/eye.svg (89%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/sun.svg (91%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/angel.svg (92%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/fire-shield.svg (94%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/ice-shield.svg (96%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/mage-shield.svg (98%)
foundry.js:35072 Foundry VTT | Loaded icons/svg/holy-shield.svg (100%)
6foundry.js:19220 You are calling PlaceableObject#getFlag which has been deprecated in favor of Document#getFlag. Support will be removed in 0.9.0
getFlag @ foundry.js:19220
foundry.js:2033 Foundry VTT | Rendering HeadsUpDisplay
foundry.js:2033 Foundry VTT | Rendering SceneDirectory
libWrapper-api.js:425 libWrapper: Registered a wrapper for 'Sound.prototype.play' by module 'CommunityLighting' with type WRAPPER.
libWrapper-api.js:425 libWrapper: Registered a wrapper for 'PointSource.prototype.animate' by module 'CommunityLighting' with type WRAPPER.
libWrapper-api.js:425 libWrapper: Registered a wrapper for 'SceneDirectory.prototype._onClickEntityName' by module 'df-scene-enhance' with type MIXED.
libWrapper-api.js:425 libWrapper: Registered a wrapper for 'SceneDirectory.prototype._getEntryContextOptions' by module 'df-scene-enhance' with type MIXED.
module.js:6 Illandril's Token Hud Scale | Settings Initialized - already on 2
mmi.js:19 Mildly Magical Inspiration | Version 2.0.0
foundry.js:9736 The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0
get _id @ foundry.js:9736
foundry.js:10432 Foundry VTT | Constructed index of Compendium pack fxmaster.fxmaster containing 5 entries
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/actors-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-log.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/combat-tracker.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/compendium-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/items-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/journal-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/playlists-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/settings.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/tables-directory.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template modules/mmi/templates/ui-button.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/hud/hud.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template modules/df-scene-enhance/templates/scene-directory.hbs
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/dice/tooltip.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-message.html
foundry.js:3591 Foundry VTT | Retrieved and compiled template modules/SoundBoard/templates/partials/packagecard.hbs
foundry.js:53581 Foundry VTT | Activating pending audio playback with user gesture.
foundry.js:2033 Foundry VTT | Rendering u
foundry.js:2033 Foundry VTT | Rendering p
2foundry.js:3591 Foundry VTT | Retrieved and compiled template templates/app-window.html
foundry.js:2033 Foundry VTT | Rendering y`


No difference regarding trying it from in-client or from an external browser with GM-privileges.

**Comment by ben** [comment]
Hmm. There's nothing in that console log that shows an exception or anything, but it also doesn't seem complete? When I do a clean reload, the `Retrieved and compiled template templates/dice/tooltip.html` line is about 60% of the way through.

Here's what it looks like when I try what you're describing. Are we doing different things?


https://user-images.githubusercontent.com/39902/123272441-f8eba680-d4be-11eb-9b52-fcc1273795d5.mp4

**Comment by Aritei** [comment]
No, that's not what I was trying.

But it's a functional workaround, thanks.

I clicked edit -> delete asset, which doesn't work.

**Comment by ben** [comment]
Aha! Now I understand what's broken. That should be easy to fix.
