### ISSUE TITLE
Compendium link not directing to Compendium correctly

### ISSUE THREAD

**Issue by midnightblackwolf** [ben/foundry-ironsworn#529]
So within An asset, the links to the compendium work correctly when they are in one of the 'Abilities'.
EG: `<p>Example where the links work:
One @Compendium[foundry-ironsworn.ironswornmoves.fdb51ee928b4fca2]{Endure Harm} or the other @Compendium[foundry-ironsworn.ironswornmoves.e09e2fc8bb709320]{Endure Stress}</p>`
Takes you to the correct move in the Character side sheet, and opens it. [Expected behaviour]

![Works](https://user-images.githubusercontent.com/1176921/200397700-fefe543a-60d0-43ec-86ba-00d32282c1b6.jpg)

But if those same compendium references are used in the Asset 'Description' they pop up a Move editing box instead of just directing to the move in the Character sheet side panel. [Not the expected behaviour]
EG.
`<p>When you ask the great jaguar spirit to inhabit your body, roll +wits. On a strong hit, you transform into a full jaguar, @Compendium[foundry-ironsworn.ironswornmoves.fdb51ee928b4fca2]{Endure Harm} (1) and take +6 nuna. ...</p>`

![Doesn't Work](https://user-images.githubusercontent.com/1176921/200397734-4d686fea-3eac-409b-9adb-62cb457ce7a0.jpg)

**Comment by ben** [comment]
Ha, nice catch! Super easy fix, it'll go out in the next release. Thanks!
