### ISSUE TITLE
Move Items doesn't keep custom description

### ISSUE THREAD

**Issue by gothalo** [ben/foundry-ironsworn#53]
I have created a new move in the items sections. I have changed its default description, but when I commit my changes, it returns to its default description.

This is the edited description
<img width="524" alt="Screenshot 2021-06-29 at 13 22 11" src="https://user-images.githubusercontent.com/2480316/123789907-f8e41000-d8dd-11eb-8b4b-d9ce3127a2f8.png">
This is what I see when commit my changes
<img width="526" alt="Screenshot 2021-06-29 at 13 22 01" src="https://user-images.githubusercontent.com/2480316/123789917-fb466a00-d8dd-11eb-8400-bdceb9a7eb67.png">

Curiously, when I open for edit again the description, it doesn't matter if I have restarted my foundry server, I still get my description.

**Comment by ben** [comment]
Whoops! I _think_ that changed in the 0.8.x series, and I haven't looked at that sheet since then. I'll roll a release and get this fix out there. Thanks!

**Comment by ben** [comment]
Done! Update your system and it should be fixed.

**Comment by gothalo** [comment]
Thank you very much. Now it works fine
