### ISSUE TITLE
Can't edit shared actor name or portrait

### ISSUE THREAD

**Issue by kdmcdrm** [ben/foundry-ironsworn#58]
Shared actor sheet is great, but it'd be nice to be able to rename it and edit the portrait (to get rid of mystery man in the actor list). I tried to switch the sheet to a normal character sheet temporarily to edit those fields but it doesn't allow it.

This is a "nice to have," I'd set low priority if I knew how :).

**Comment by ben** [comment]
Done! Bump to 0.4.9 and you should get it.
