### ISSUE TITLE
Incompatibility with PopOut! module

### ISSUE THREAD

**Issue by Purzelkater** [ben/foundry-ironsworn#670]
It seems like there is an issue with the _PopOut!_ module if the moves are extracted as a standalone window. It looks like the functions still there (I can click on it), but the icons are gone. 

![moves_popout](https://user-images.githubusercontent.com/44810275/223492268-1dd4710a-aa44-431f-a620-6ee5467df318.png)

Also, if I click the (invisible) dice icon, the window is placed inside the moves window and not as a popup (or new window).

![moves_inside](https://user-images.githubusercontent.com/44810275/223492509-28916eed-1cde-49d3-a16f-f849b0a50656.png)

**Comment by ben** [comment]
@rsek do you think the first part is about sprite sheets maybe?

**Comment by rsek** [comment]
> @rsek do you think the first part is about sprite sheets maybe?

that'd make sense. they're just accessing the inlined SVG with local anchor references, so if popout can't get at the original window (and its window doesn't include the sprite sheet), it's gonna be SOL.

two possible workarounds off the top of my head:
1) figure out a way to provide the inline sprite sheet to *all* applications.
2) provide the sprite sheet as a static asset, e.g. an actual `sprite-sheet.svg` whose contents can then be referenced with something like `/systems/assets/sprite-sheet.svg#some-sprite`. not sure what implications this would have on other components. at that point we might be able to ditch the fallback single file SVGs used for icons managed by foundry, which would be nice.

main reason i haven't done #2 is that i haven't been able to find a satisfactory vite plugin for the purpose.

**Comment by rsek** [comment]
@Purzelkater sorry for the wait, this should be fixed in the latest release, let me know if it works out for you :)
