### ISSUE TITLE
Try to do less in-memory caching of compendiums

### ISSUE THREAD

**Issue by ben** [ben/foundry-ironsworn#699]
Had a chat on the League discord not long ago, and it got me thinking. We're doing a lot of work to keep the compendiums fresh. I wonder if it might instead be better to do something like `pack.getIndex({fields: ['system.dfid']})` to get index information, and then do async loads when we need actual documents.

**Comment by rsek** [comment]
already told ben about this a while back, but for posterity: i've experimented with this on local branches, and it does work. it can even point at flags, so we could index e.g. RollTables with `flags.foundry-ironsworn.dfid`

**Comment by ben** [comment]
Managed to finish this with #1023; we're no longer doing any `pack.getDocuments()` calls, except when showing a setting-truths dialog, which is okay because at that point we need them all.
