### ISSUE TITLE
'Site' item type does not open

### ISSUE THREAD

**Issue by orffen** [ben/foundry-ironsworn#84]
The 'site' item type does not open on my FoundryVTT 0.8.8 install - I get the following error in the console:

> Uncaught TypeError: Cannot read property 'rendered' of null
    at ItemDirectory._onClickEntityName (foundry.js:23639)
    at HTMLOListElement.dispatch (jquery.min.js:2)
    at HTMLOListElement.v.handle (jquery.min.js:2)

**Comment by ben** [comment]
Oh yeah, I put that in there in the initial version, but it doesn't have a sheet or anything. I'll remove it as an option so nobody gets confused.

**Comment by ben** [comment]
Just pushed a tag. Wait 10 minutes and update your system, and the "site" option should be gone from the new-item dropdown. Thanks for the tip!
